version: "3.8"

services:
  database:
    container_name: database
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data 
      # - ./pkg/utility/createDB.sql:/docker-entrypoint-initdb.d/

volumes:
  db: